-- =====================================================================
-- NextGen Talent Matrix - Database Schema (Supabase / PostgreSQL)
-- =====================================================================

-- Table 1: Voice Roadmap Sessions
-- Stores information generated by Module 1 (Voice-to-Roadmap)
CREATE TABLE IF NOT EXISTS roadmap_sessions (
  id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE,
  transcript TEXT NOT NULL,
  career_title TEXT NOT NULL,
  required_skills TEXT[] DEFAULT '{}',
  steps_count INTEGER DEFAULT 0,
  roadmap_data JSONB,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Table 2: Skill Analyses
-- Stores comparative results from Module 2 (Skill-Gap Analyzer)
CREATE TABLE IF NOT EXISTS skill_analyses (
  id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE,
  career_title TEXT NOT NULL,
  match_percentage INTEGER DEFAULT 0,
  matched_skills_count INTEGER DEFAULT 0,
  missing_skills TEXT[] DEFAULT '{}',
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Enable Row Level Security (RLS)
ALTER TABLE roadmap_sessions ENABLE ROW LEVEL SECURITY;
ALTER TABLE skill_analyses ENABLE ROW LEVEL SECURITY;

-- Enable RLS Policies that respect user_id checks
CREATE POLICY "Allow individual insert to roadmap_sessions" ON roadmap_sessions
  FOR INSERT WITH CHECK (auth.uid() = user_id OR user_id IS NULL OR auth.uid() IS NULL);

CREATE POLICY "Allow individual select from roadmap_sessions" ON roadmap_sessions
  FOR SELECT USING (auth.uid() = user_id OR user_id IS NULL OR auth.uid() IS NULL);

CREATE POLICY "Allow individual delete from roadmap_sessions" ON roadmap_sessions
  FOR DELETE USING (auth.uid() = user_id OR user_id IS NULL OR auth.uid() IS NULL);

CREATE POLICY "Allow individual insert to skill_analyses" ON skill_analyses
  FOR INSERT WITH CHECK (auth.uid() = user_id OR user_id IS NULL OR auth.uid() IS NULL);

CREATE POLICY "Allow individual select from skill_analyses" ON skill_analyses
  FOR SELECT USING (auth.uid() = user_id OR user_id IS NULL OR auth.uid() IS NULL);

CREATE POLICY "Allow individual delete from skill_analyses" ON skill_analyses
  FOR DELETE USING (auth.uid() = user_id OR user_id IS NULL OR auth.uid() IS NULL);

-- Table 3: User Resumes
-- Stores editable resume profile data from Module 2 (Skill-Gap Analyzer)
CREATE TABLE IF NOT EXISTS user_resumes (
  id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  user_id UUID UNIQUE REFERENCES auth.users(id) ON DELETE CASCADE,
  personal_name TEXT DEFAULT '',
  objective TEXT DEFAULT '',
  education JSONB DEFAULT '[]'::jsonb,
  experience JSONB DEFAULT '[]'::jsonb,
  projects JSONB DEFAULT '[]'::jsonb,
  skills JSONB DEFAULT '[]'::jsonb,
  achievements JSONB DEFAULT '[]'::jsonb,
  resume_file_name TEXT,
  resume_file_type TEXT,
  resume_file_size INTEGER,
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Enable Row Level Security (RLS)
ALTER TABLE user_resumes ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Allow individual insert to user_resumes" ON user_resumes
  FOR INSERT WITH CHECK (auth.uid() = user_id OR user_id IS NULL OR auth.uid() IS NULL);

CREATE POLICY "Allow individual select from user_resumes" ON user_resumes
  FOR SELECT USING (auth.uid() = user_id OR user_id IS NULL OR auth.uid() IS NULL);

CREATE POLICY "Allow individual update to user_resumes" ON user_resumes
  FOR UPDATE USING (auth.uid() = user_id OR user_id IS NULL OR auth.uid() IS NULL);

CREATE POLICY "Allow individual delete from user_resumes" ON user_resumes
  FOR DELETE USING (auth.uid() = user_id OR user_id IS NULL OR auth.uid() IS NULL);
