"use client";

import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";
import styles from "./page.module.css";

export default function TermsPage(): React.JSX.Element {
  return (
    <>
      <Navbar />

      <main className={styles.pageWrapper}>
        <div className={styles.pageGlow} />
        <div className={styles.container}>
          <div className={styles.header}>
            <h1 className={styles.title}>Terms of Use</h1>
            <p className={styles.subtitle}>Last updated: August 15, 2026</p>
          </div>

          <div className={styles.contentCard}>
            <div className={styles.textBlock}>
              <p>
                Welcome to NextTalent! By accessing or using our platform, website, and services, you agree to be bound by these Terms of Use. Please read them carefully.
              </p>

              <h2>1. Acceptance of Terms</h2>
              <p>
                By using NextTalent, you agree to comply with and be bound by these terms. If you do not agree to all of these terms, you should not access or use the platform. We reserve the right to modify these terms at any time without prior notice.
              </p>

              <h2>2. Use of Services</h2>
              <p>
                NextTalent provides educational tools, AI roadmap generation, skill-gap analysis, and course recommendation services. You agree to use these services only for lawful, personal, and non-commercial educational purposes.
              </p>
              <ul>
                <li>You may not use our services to automate requests or scrape data.</li>
                <li>You may not impersonate any person or entity or misrepresent your affiliation.</li>
                <li>You may not upload malicious code, viruses, or use tools that could disrupt the service infrastructure.</li>
              </ul>

              <h2>3. AI-Generated Content Disclaimer</h2>
              <p>
                The roadmaps, skill analyses, and other feedback generated by NextTalent's integrated AI engines (such as Gemini 2.5 Flash / 3.1 Flash-Lite) are for informational and planning purposes only.
              </p>
              <ul>
                <li>We do not guarantee the absolute accuracy, completeness, or suitability of any generated roadmap or advice.</li>
                <li>Course recommendations are suggested pathways, and we are not affiliated with or responsible for the content of third-party platforms (like Coursera, Udemy, etc.).</li>
              </ul>

              <h2>4. Intellectual Property</h2>
              <p>
                All elements of the NextTalent platform, including styling, design tokens, logo assets, brand marks, and code, are the intellectual property of NextTalent and its developers. You may not copy, modify, distribute, or create derivative works without express permission.
              </p>

              <h2>5. Limitation of Liability</h2>
              <p>
                NextTalent is provided on an "as is" and "as available" basis. Under no circumstances shall NextTalent or its creators be liable for any direct, indirect, incidental, or consequential damages resulting from the use or inability to use our platform or recommendations.
              </p>

              <h2>6. Contact Us</h2>
              <p>
                For questions or suggestions regarding these Terms of Use, please reach out to us:
              </p>
              <p>
                ✉️ Email: <a href="mailto:onlytheone1092@gmail.com" style={{ color: "var(--accent-400)", textDecoration: "none", fontWeight: 600 }}>onlytheone1092@gmail.com</a>
              </p>
            </div>
          </div>
        </div>
      </main>

      <Footer />
    </>
  );
}
